---
host: service-manual
buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git
memory: 256M
instances: 1
env:
  NODE_MODULES_CACHE: false
path: ./
command: node server/index.js

applications:
- name: service-manual-blue
- name: service-manual-green
